name: pikpak_auto_invite
on:
  push:
    branches: [ main ]
    paths:
      - '**'
      - '!.gitignore'
      - '!README.md'
  schedule:
    # 每隔两天运行一次，总计运行30次后停止
    - cron: '0 2 */2 * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Time
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - name: Run
        env:
          INVITE_CODE: ${{secrets.INVITE_CODE}}
        run: python run.py
      - name: Check if run count is within limit
        run: |
          if [ ${{ github.run_number }} -le 30 ]; then
            echo "Continue with job execution."
          else
            echo "Reached maximum run count. Stopping further executions."
            exit 0
          fi
